version: '3.9'

services:
  app:
    image: tcatovic/dotnet:latest
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    depends_on:
      - db
    volumes:
      - ..:/workspace:cached
  db:
    image: tcatovic/sqlserver:latest